---
title: "creel_mark_rate_comparison"
editor: visual
---

# packages

```{r}
library("CreelEstimateR")
library("suncalc")
library("tidyverse")
library("patchwork")
library("gt")
library("here")
library("mgcv")
library("gratia")
library("framrsquared")
library("cli")
library("here")
```

### mark rates using catch estimates

```{r}
source(here("scripts/prepare_creel_data.R"))
combined = read_csv(here("cleaned_data/key_dataframes/bss_combined.csv")) ##ugly column type specs, but read_csv was misidentifying sex and run types.
# read in creel catch estimates for the 2023 Nisqually


total_mark_rates <- combined |> 
  group_by(est_cg) |> 
  summarise(
    total = sum(mean)
  ) |> 
  pivot_wider(names_from = est_cg, values_from =  total) |> 
  rename(total_ad_encounters = `Chinook_Adult_AD_Kept|Released`, total_encounters = `Chinook_Adult_AD|UM|UNK_Kept|Released`) |> 
  mutate(
    mark_rate = total_ad_encounters/total_encounters
  )

stratum_total_mark_rates <- combined |> 
  group_by(section_num, day_type, angler_final, est_cg) |> 
  summarise(
    total = sum(mean)
  ) |> 
  pivot_wider(names_from = est_cg, values_from =  total) |> 
  rename(total_ad_encounters = `Chinook_Adult_AD_Kept|Released`, total_encounters = `Chinook_Adult_AD|UM|UNK_Kept|Released`) |> 
  mutate(
    mark_rate = total_ad_encounters/total_encounters
  )

# looks like bank catch is has a consistently lower mark rate than boat catch

weekly_catch_mark_rate <- combined |> 
  group_by(management_week, section_num, angler_final, est_cg) |> 
  summarise(
    total = sum(mean)
  ) |> 
  pivot_wider(names_from = est_cg, values_from =  total) |> 
  rename(total_ad_encounters = `Chinook_Adult_AD_Kept|Released`, total_encounters = `Chinook_Adult_AD|UM|UNK_Kept|Released`) |> 
  mutate(
    mark_rate = total_ad_encounters/total_encounters
  )

weekly_catch_mark_rate |> 
  filter(section_num == 1) |> 
  ggplot(aes(management_week, mark_rate)) +
  geom_point() +
  facet_wrap(vars(section_num, angler_final))


# catch_totals_weekly |> 
#   filter(section_num == 2) |> 
#   filter(!(section_num == 2 & angler_final == "Bank")) |> 
#   ggplot(aes(management_week, mark_rate)) +
#   geom_point() +
#   facet_wrap(vars(section_num, angler_final))


### look at weekly mark rates calculated using expanded catch estimates

# create plots to examine potential patterns in catch/mark rate by design strata: section_num (area), day_type (weekday/weekend), anger_final (bank vs boat angler)

# aggregating over section_num and angler_final
combined |> select(event_date, management_week, section_num, day_type, angler_final, est_cg, mean) |> 
  filter(section_num == 1) |> 
  group_by(management_week, est_cg) |> 
  summarise(
    total = sum(mean)
  ) |> 
  pivot_wider(names_from = est_cg, values_from =  total) |> 
  rename(total_ad_encounters = `Chinook_Adult_AD_Kept|Released`, total_encounters = `Chinook_Adult_AD|UM|UNK_Kept|Released`) |> 
  mutate(
    mark_rate = total_ad_encounters/total_encounters
  ) |> 
  ggplot(aes(management_week, mark_rate)) +
  geom_point(size = 2) +
  scale_y_continuous(limits = c(0,1))


# plotted by angler type 
combined |> select(event_date, management_week, section_num, day_type, angler_final, est_cg, mean) |> 
  filter(section_num == 1) |> 
  group_by(management_week, section_num, angler_final, est_cg) |> 
  summarise(
    total = sum(mean)
  ) |> 
  pivot_wider(names_from = est_cg, values_from =  total) |> 
  rename(total_ad_encounters = `Chinook_Adult_AD_Kept|Released`, total_encounters = `Chinook_Adult_AD|UM|UNK_Kept|Released`) |> 
  mutate(
    mark_rate = total_ad_encounters/total_encounters
  ) |> 
  ggplot(aes(management_week, mark_rate, fill = angler_final, color = angler_final)) +
  geom_point(size = 2) +
  scale_y_continuous(limits = c(0,1))

# plotting by angler type, there appears to be a systematic offset between bank and boat, similar to the net vs. sport pattern??

# by viewing the data in light of the design strata, are there clues as to where potential bias are introduced in the data, regarding angler type, time period, or spatial area?

```

```{r}
# plot daily catch time series for three catch groups to visualize mark rate dynamics over time
combined |> 
  # filter(est_cg %in% c("Chinook_Adult_UM_Released", "Chinook_Adult_AD_Kept|Released", "Chinook_Adult_AD|UM|UNK_Kept|Released)) |> 
  filter(section_num == 1 & angler_final == "Bank") |> 
  ggplot(aes(x = event_date, y = quantile_median_50, fill = est_cg, color = est_cg)) +
  geom_ribbon(aes(ymin = quantile_lower_2_5, ymax = quantile_upper_97_5), alpha = 0.2, color = "transparent") +
  geom_line(lwd = 1) +
  ylab("Median (50%) catch") +
  xlab("Date") +
  # labs(color = "Angler type", fill = "Angler type") +
  scale_x_date() +
  theme_bw() +
  facet_wrap(~section_num + angler_final)

# UM released and AD encounters track closely - is a significant proportion of the UM Chinook catch unmarked hatchery fish? 
# generate catch estimates for pinks and plot them here?
# generate catch estimates for AD Kept Chinook - these would be considered more reliable due to sampling

```

### Basic plots

```{r}

## summarize treaty net data
data_treaty_net <- readr::read_csv("./cleaned_data/tidy_20-years-net-mark-rates.csv")
net_mr_2023 <- data_treaty_net |> 
  filter(year == 2023) |> 
  pivot_wider(names_from = fin_mark, values_from = catch) |> 
  summarize(AD = sum(AD), 
            UM = sum(UM)) |> 
  mutate(MR = AD/(AD + UM))

## summarize raw creel data
catch = read_csv(here("cleaned_data/key_dataframes/creel_interview_catch.csv"),
                 col_types = c("cccccccncncDcnnn")) ##ugly column type specs, but read_csv was misidentifying sex and run types.

catch.mr.2023 = catch |> 
  filter(year == 2023) |> 
  pivot_wider(names_from = fin_mark, values_from = fish_count) |> 
  summarize(AD = sum(AD, na.rm = T), 
            UM = sum(UM, na.rm = T)) |> 
  mutate(MR = AD/(AD + UM))

mr.summary = data.frame(
  source = c("treaty net", "raw creel interview", "bss"),
  mr = c(net_mr_2023$MR, total_mark_rates$mark_rate, catch.mr.2023$MR),
  year = c(2023, 2023, 2023)
)

mr.summary |> 
  ggplot(aes(x = source, y = mr, fill = source))+
  geom_col()+
  ylim(0, 1)+
  labs(title = "Overview of estimated mark rate, 2023",
       subtitle = "Caveat: need to double check methods", 
       y = "mark rate")+
  theme_bw(base_size = 18)+
  theme(legend.position = "")

```

```{r}
summarize_MR = function(.data, var){
  .data |> 
    group_by(.data[[var]], est_cg)|> 
    summarise(
      total = sum(mean)
    ) |> 
    ungroup() |> 
    pivot_wider(names_from = est_cg, values_from =  total) |> 
    rename(total_ad_encounters = `Chinook_Adult_AD_Kept|Released`, total_encounters = `Chinook_Adult_AD|UM|UNK_Kept|Released`) |> 
    mutate(
      mark_rate = total_ad_encounters/total_encounters
    )
}

gp1 = combined |> 
  summarize_MR("angler_final") |> 
  ggplot(aes(x = angler_final, y = mark_rate, fill = angler_final))+
  geom_col()+
  ggtitle("Angler type")+
  theme_bw(base_size = 18)+
  theme(legend.position = "none")

gp2 = combined |> 
  summarize_MR("day_type")|> 
  ggplot(aes(x = day_type, y = mark_rate, fill = day_type))+
  geom_col()+
  ggtitle("Day type")+
  theme_bw(base_size = 18)+
  theme(legend.position = "none")

gp3 = combined |> 
  summarize_MR("section_num")|> 
  ggplot(aes(x = as.factor(section_num), y = mark_rate, fill = as.factor(section_num)))+
  geom_col()+
  ggtitle("Section")+
  xlab("Section")+
  theme_bw(base_size = 18)+
  theme(legend.position = "none")

(gp1 | gp2 | gp3) & plot_annotation(title = "2023 BSS output by strata", theme = theme(title = element_text(size = rel(2))))

```

```{r}

# this may be done incorrectly, ignore for now! 

# strata_compare <- combined |> select(event_date, management_week, section_num, day_type, angler_final, est_cg, mean) |>
#   filter(!(section_num == 2 & angler_final == "Bank")) |> 
#   mutate(
#     section_num = as.factor(section_num),
#     day_type = as.factor(day_type),
#     angler_final = as.factor(angler_final)
#   ) |> 
#   pivot_wider(names_from = est_cg, values_from =  mean) |> 
#    rename(ad_encounters = `Chinook_Adult_AD_Kept|Released`, total_encounters = `Chinook_Adult_AD|UM|UNK_Kept|Released`) |> 
#   mutate(
#     mark_rate = ad_encounters/total_encounters
#   )
# 
# strata_compare |> 
#   pivot_longer(cols = c(section_num, day_type, angler_final), names_to = "design_strata", values_to = "strata_levels") |> 
#   ggplot(aes(mark_rate, strata_levels)) +
#   geom_boxplot() +
#   facet_wrap(.~design_strata)


```

```{r}

# test out the use of the newly packaged up fetch_dwg function, creating a vector of the names of the Nisqually fisheries we want to pull into R

# define fisheries we want data for
# fisheries <- c("Nisqually salmon 2021", "Nisqually salmon 2022", "Nisqually salmon 2023")
# 
# # download the data from data.wa.gov
# datapull <- set_names(fisheries) |>
#   map(~fetch_dwg(fishery_name = .x))
# 
# interviews <- datapull$`Nisqually salmon 2023`$interview |>
#   bind_rows(datapull$`Nisqually salmon 2022`$interview, datapull$`Nisqually salmon 2021`$interview)
# 
# # bind date and waterbody data to the creel interview-based catch records
# catch <- datapull$`Nisqually salmon 2023`$catch |>
#   bind_rows(datapull$`Nisqually salmon 2022`$catch, datapull$`Nisqually salmon 2021`$catch) |>
#   left_join(interviews |>
#               select(interview_id, event_date, water_body),
#             by = "interview_id") |>
#   mutate(
#     year = year(event_date),
#     month = month(event_date)
#   )


```
